const ADDTODO = 'ADDTODO'
const UPDATETODO = 'UPDATETODO'
const DELETETODO = 'DELETETODO'
const UPDATEALLTODO = 'UPDATEALLTODO'
const DELETECHECKTODO = 'DELETECHECKTODO'

export { ADDTODO, UPDATETODO, DELETETODO, UPDATEALLTODO, DELETECHECKTODO }
